### ISSUE TITLE
win10 npm start 启动报错

### ISSUE THREAD

**Issue by lius123** [qld-cf/electron-react-tpl#18]
[electron] scripts/main-build.js � Electron webpack 相关报错
[electron] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[electron]     at validateString (internal/validators.js:117:11)
[electron]     at Object.join (path.js:375:7)
[electron]     at D:\moushi\desktop_im\scripts\main-build.js:32:13
[electron]     at Hook.eval [as callAsync] (eval at create (D:\moushi\desktop_im\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
[electron]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\moushi\desktop_im\node_modules\tapable\lib\Hook.js:18:14)
[electron]     at D:\moushi\desktop_im\node_modules\webpack\lib\Compiler.js:1114:33
[electron]     at finalCallback (D:\moushi\desktop_im\node_modules\webpack\lib\Compilation.js:2249:11)
[electron]     at D:\moushi\desktop_im\node_modules\webpack\lib\Compilation.js:2540:11
[electron]     at Hook.eval [as callAsync] (eval at create (D:\moushi\desktop_im\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
[electron]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\moushi\desktop_im\node_modules\tapable\lib\Hook.js:18:14) {
[electron]   code: 'ERR_INVALID_ARG_TYPE'
[electron] }
[electron] scripts/main-build.js Watching Ended.

**Comment by qld-cf** [comment]
> [electron] scripts/main-build.js � Electron webpack 相关报错 [electron] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined [electron] at validateString (internal/validators.js:117:11) [electron] at Object.join (path.js:375:7) [electron] at D:\moushi\desktop_im\scripts\main-build.js:32:13 [electron] at Hook.eval [as callAsync] (eval at create (D:\moushi\desktop_im\node_modules\tapable\lib\HookCodeFactory.js:33:10), :7:1) [electron] at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\moushi\desktop_im\node_modules\tapable\lib\Hook.js:18:14) [electron] at D:\moushi\desktop_im\node_modules\webpack\lib\Compiler.js:1114:33 [electron] at finalCallback (D:\moushi\desktop_im\node_modules\webpack\lib\Compilation.js:2249:11) [electron] at D:\moushi\desktop_im\node_modules\webpack\lib\Compilation.js:2540:11 [electron] at Hook.eval [as callAsync] (eval at create (D:\moushi\desktop_im\node_modules\tapable\lib\HookCodeFactory.js:33:10), :4:1) [electron] at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\moushi\desktop_im\node_modules\tapable\lib\Hook.js:18:14) { [electron] code: 'ERR_INVALID_ARG_TYPE' [electron] } [electron] scripts/main-build.js Watching Ended.

无法复现；可以再提供下node版本，全局electron版本

**Comment by qld-cf** [comment]
> [electron] scripts/main-build.js � Electron webpack 相关报错 [electron] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined [electron] at validateString (internal/validators.js:117:11) [electron] at Object.join (path.js:375:7) [electron] at D:\moushi\desktop_im\scripts\main-build.js:32:13 [electron] at Hook.eval [as callAsync] (eval at create (D:\moushi\desktop_im\node_modules\tapable\lib\HookCodeFactory.js:33:10), :7:1) [electron] at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\moushi\desktop_im\node_modules\tapable\lib\Hook.js:18:14) [electron] at D:\moushi\desktop_im\node_modules\webpack\lib\Compiler.js:1114:33 [electron] at finalCallback (D:\moushi\desktop_im\node_modules\webpack\lib\Compilation.js:2249:11) [electron] at D:\moushi\desktop_im\node_modules\webpack\lib\Compilation.js:2540:11 [electron] at Hook.eval [as callAsync] (eval at create (D:\moushi\desktop_im\node_modules\tapable\lib\HookCodeFactory.js:33:10), :4:1) [electron] at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\moushi\desktop_im\node_modules\tapable\lib\Hook.js:18:14) { [electron] code: 'ERR_INVALID_ARG_TYPE' [electron] } [electron] scripts/main-build.js Watching Ended.

升级了版本；应该已经修复，可以再试下
